name = "admin-eromanga"
compatibility_date = "2024-06-01"
pages_build_output_dir = "./.svelte-kit/cloudflare"  # ถ้าใช้ SvelteKit
compatibility_flags = ["nodejs_compat"]             # สำหรับใช้ Node API

# เชื่อมฐานข้อมูล D1
[[d1_databases]]
binding = "DB"  # ใช้ในโค้ด: env.DB
database_name = "eromanga_db"
database_id = "35d422ed-324c-4016-a712-31a4878f25f0"

# Environment: Production (custom domain)
[env.production]
routes = ["admin.eromanga.net/*"]
