name = "admin-eromanga"
compatibility_date = "2024-06-01"
pages_build_output_dir = ".svelte-kit/output/client"  # แก้ path ตรงนี้ให้ถูกต้อง
compatibility_flags = ["nodejs_compat"]             # สำหรับใช้ Node API

# เชื่อมฐานข้อมูล D1 (ระดับ global)
[[d1_databases]]
binding = "DB"  # ใช้ในโค้ด: env.DB
database_name = "eromanga_db"
database_id = "35d422ed-324c-4016-a712-31a4878f25f0"

# Environment: Production (custom domain + routes)
[env.production]
routes = ["admin.eromanga.net/*"]

# ต้องเพิ่ม d1_databases อีกครั้งสำหรับ environment production
[[env.production.d1_databases]]
binding = "DB"
database_name = "eromanga_db"
database_id = "35d422ed-324c-4016-a712-31a4878f25f0"
